spring:
  application:
    name: msvc-notification
  config:
    import: optional:configserver:http://config-service:8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/
