server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: admins
          uri: lb://msvc-admin
          predicates:
            - Path=/api/v1/admins/**
        - id: appointments
          uri: lb://msvc-appointment
          predicates:
            - Path=/api/v1/appointments/**
        - id: billings
          uri: lb://msvc-billing
          predicates:
            - Path=/api/v1/bills/**
        - id: doctors
          uri: lb://msvc-doctor
          predicates:
            - Path=/api/v1/doctors/**
        - id: medicalRecords
          uri: lb://msvc-medicalrecord
          predicates:
            - Path=/api/v1/medical-record/**
        - id: notifications
          uri: lb://msvc-notification
          predicates:
            - Path=/api/v1/notifications/**
        - id: patients
          uri: lb://msvc-patient
          predicates:
            - Path=/api/v1/patients/**
    config:
      import: optional:configserver:http://config-service:8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/
  instance:
    hostname: eureka-server
