server:
  port: 8091

spring:
  application:
    name: msvc-patient
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://patient-db:3306/patientDB
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  instance:
    hostname: patient-service
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/