server:
  port: 8096

spring:
  application:
    name: msvc-notification
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://notification-db:5432/notificationDB
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    hostname: eureka-service
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/