server:
  port: 8097

spring:
  application:
    name: msvc-admin
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://admin-db:3306/adminDB
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  instance:
    hostname: eureka-service
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
