server:
  port: 8094

spring:
  application:
    name: msvc-billing
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://billing-db:5432/billingDB
    username: postgres
    password: 1234
  jpa:
    hibernate:
     ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/